[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "James Bennett"},
]
maintainers = [
  {name = "James Bennett"}
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.1",
  "Framework :: Django :: 5.2",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Utilities",
]
name = "django-contact-form"
description = "A generic contact-form application for Django."
dependencies = [
    "Django>=4.2,!=5.0.*",
]
keywords = ["django", "email", "contact-form"]
license = {text = "BSD-3-Clause"}
readme = "README.rst"
requires-python = ">=3.9"
version = "5.2.0"

[project.urls]
"Documentation" = "https://django-contact-form.readthedocs.io/"
"Source Code" = "https://github.com/ubernostrum/django-contact-form"

[project.optional-dependencies]
akismet = [
    "akismet>=24.5.0",
]
[dependency-groups]
tests = ["nox"]

[tool.bandit]
skips = ["B101"]

[tool.black]
target-version = ["py39", "py310", "py311", "py312", "py313"]

[tool.check-manifest]
ignore-bad-ideas = ["*.mo"]

[tool.check-wheel-contents]
ignore = ["W004"]

[tool.coverage.paths]
source = ["src", ".nox/tests_with_coverage*/**/site-packages"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __str__",
  "raise NotImplementedError",
]
fail_under = 100

[tool.coverage.run]
branch = true
parallel = true
source = ["django-contact-form"]

[tool.interrogate]
fail-under = 100
ignore-init-method = true
ignore-init-module = true
ignore-magic = true

[tool.isort]
profile = "black"

[tool.pdm]
distribution = true

[tool.pdm.build]
source-includes = [
    ".editorconfig",
    ".flake8",
    ".pre-commit-config.yaml",
    ".readthedocs.yaml",
    "AUTHORS",
    "CONTRIBUTING.rst",
    "docs/",
    "noxfile.py",
    "pdm.lock",
    "runtests.py",
    "tests/",
]

[tool.pylint]
disable = ["duplicate-code"]
